name: Deploy Backend
on:
  push:
    branches: [ "main" ]
    paths: [ "backend/**" ]

jobs:
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code tu GitHub
        uses: actions/checkout@v4
      
      - name: Day code len Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          server-dir: /htdocs/api/