name: Deploy Frontend
on:
  push:
    branches: [ "main" ]
    paths: [ "frontend/**" ]

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code tu GitHub
        uses: actions/checkout@v4
      
      - name: Ghi gio cap nhat vao HTML
        run: |
          
      - name: Day code len Hosting (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/
          server-dir: /htdocs/